### ISSUE TITLE
Missing Translation for Order Processing Fee

### ISSUE THREAD

**Issue by chrisaligent** [aligent/orocommerce-fees-bundle#22]
The Oro `Order` entity has the `processingFee` field added to it (see https://github.com/aligent/orocommerce-fees-bundle/blob/main/src/Aligent/FeesBundle/Migrations/Schema/v1_0/AddProcessingFeeToOrders.php )

However no Translation exists for this.

It should be added via:
```yaml
oro.order.processing_fee.label: 'Processing Fee'
```

**Comment by carbsrule** [comment]
Resolved in v5.0.4
